### ISSUE TITLE
ISO 8601 datetime format

### ISSUE THREAD

**Issue by bbaassssiiee** [aioue/ansible-plugin-profile#1]
As Ansible log parser  I would rather see:

2015-06-30T13:34:28 +02:00 (0:00:06.616)

Instead of:

Tuesday 30 June 2015  13:34:28 +0200 (0:00:06.616)

http://www.iso.org/iso/home/standards/iso8601.htm

**Comment by aioue** [comment]
:+1: should be straightforward to add a switch in to choose formats.

**Comment by bbaassssiiee** [comment]
this repo is neglected
